version: "3.9"
services:
  django-app:
    env_file:
      - ./.env
    container_name: django-app-continer
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: ./start.sh

